##
##	[makefile.config]
##	Created by Micael Levi on 09/09/2016
##	Copyright (c) 2016 mllc@icomp.ufam.edu.br; All rights reserved.
##

#
#	Global configuration for makefile
#

#
# (em relacao ao arquivo makefile)
# MAIN		= nome do programa executavel
# SRCSDIR	= caminho dos arquivos .c
# INCDIR	= caminho dos arquivos .h (deve estar na mesma pasta que os codigos-fonte)
# INCLUDES 	= opcaoo para incluir arquivos cabecalhos de outros diretorio
# CC		= comando para compilar (o arroba faz sumprimir a saida do make)
# CFLAGS	= flags para o 'CC'
# LIBS		= bibliotecas importadas
# SRCS		= nome dos arquivos de codigo-fonte com extensao .c
# _OBJS		= nome dos objetos que serao gerados (extensao .o)
# MSGUSO	= mensagem de uso do programa (exibido apos o comando make)
#

MAIN = criarIndiceRemissivo
SRCSDIR = fontes/
INCDIR = $(SRCSDIR)headers/
INCLUDES = -I $(INCDIR)
CC = @gcc
CFLAGS = -w -g
LIBS = -lm
SRCS = calcularTFIDF.c construirEDs.c contarOcorrencias.c dicionarioDinamico.c elementoDicionarios.c indiceRemissivo.c listaEncadeada.c main.c preProcesso.c tratarTexto.c vetorDinamico.c wordToInt.c
_OBJS = $(SRCSDIR)calcularTFIDF.c $(SRCSDIR)construirEDs.c $(SRCSDIR)contarOcorrencias.c $(SRCSDIR)dicionarioDinamico.c $(SRCSDIR)elementoDicionarios.c $(SRCSDIR)indiceRemissivo.c $(SRCSDIR)listaEncadeada.c $(SRCSDIR)main.c $(SRCSDIR)preProcesso.c $(SRCSDIR)tratarTexto.c $(SRCSDIR)vetorDinamico.c $(SRCSDIR)wordToInt.c
OBJS = $(_OBJS:.c=.o)

MSGUSO = "USO:\n./$(MAIN) \"caminho/do/livro\" [< \"caminho/do/arquivo/de/consultas\" 2>&-]"


######### [ VERIFICANDO PRESENÇA DO ARQUIVO TESTE] #########
PATH_BASE="testes/baseTeste"
PATH_INPUT="testes/entradas.txt"


#ifneq ("$(wildcard $("testes/baseTeste"))","")
ifneq ("$(wildcard $(PATH_BASE))","")
  TESTAVEL = true
else
  TESTAVEL = false
endif
############################################################

##########################################
UNAME := $(shell uname)
PRINT = @echo
ifeq ($(UNAME), Linux)
  # Linux flags
else ifeq ($(UNAME), Darwin)
  # OS X flags
else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  PRINT += -e
endif
##########################################
